/**
 * Deterministic prose detectors. These remain executable TypeScript rather
 * than editorial catalog data, so production validation and offline
 * evaluation can share stable rule identities without widening claims.
 */
export const reportDetectors = {
  inventedBiography: /\b(?:you(?:'|’)ve likely lived through|you have likely lived through|you learned early|learned to compensate|old,? tender spot|old(?:est)? emotional wounds?|old wound|oldest wound|never quite healed|damage is already done|not enough as you were|growing up|in (?:your )?childhood|throughout your career|in past relationships|your early home life|early[- ]home memories?|what you remember about (?:your )?home|the emotional truth of (?:a|your|the) household|a family pattern|defensive (?:reaction|pattern|strategy))\b/i,
  categoricalBehavior: /\b(?:you act before you think|you react before you think|you (?:always|usually|never) (?:know|sense|see|read|react|act|withdraw|overcommit)|your first read .* usually lands right|most of the time it works|you trust your first read|you are (?:the kind|the type|someone) who|your instinct is to|(?:your|a) (?:steady architecture|sustained effort|perceptual sharpness|resource judgment)|recovery through activity)\b/i,
  unsupportedScenario: /\b(?:replay(?:ing)? (?:a |the )?conversation|track(?:ing)? (?:texts?|replies)|returned favors?|daily chores?|walking it off|go(?:ing)? for a walk|need (?:real )?recovery time|intuition often proves right|settled (?:young|early)|old effort|past attempts?|older material|nothing is hidden from you|you clearly have|regulate closeness now|preference for demonstrating care|being someone who is simply there)\b/i,
  otherPersonInnerLife: /\b(?:another person(?:'s)?|other people(?:'s)?|someone(?:'s)?|a person(?:'s)?)\s+(?:wound|weak spot|pressure point|motive|mood|grief|need|fear|intention|reaction|response)\b|\b(?:see|sense|know|pick up on)\s+(?:what will change someone|someone(?:'s)? (?:mood|grief|need|fear|intention)|what someone else is going through|things other people have not said)\b|\b(?:tell|know|understand|see)\s+what\s+(?:another person|someone|other people)\s+(?:means?|wants?|needs?|feels?|thinks?)\b|\bbefore (?:they|someone|other people) (?:say|know)\b|\b(?:people|others|those around you)\s+(?:lean in|trust you|rely on you|look to you|experience you as|see you as)\b|\b(?:you are|you may be|you tend to be)\s+(?:often )?seen by (?:others|people) as someone who (?:knows?|understands?) what (?:they|others|people) need\b|\b(?:someone|another person|the other person)\s+(?:is|seems|appears|may be)\s+(?:holding back|withdrawing|upset|afraid|uncertain)\b|\b(?:make|leave)\s+(?:someone|people|others)\s+feel\b|\bwhat\s+(?:someone|another person|people|others)\s+(?:receive|take away|feel|think|need)\b/i,
  contextInference: /\b(?:your partner|your relationship is|your dating life|as you date|your breakup|recently separated|non[- ]?monogam(?:y|ous)|polyam(?:ory|orous)|open relationship|multiple partners?)\b/i,
  unsafeClinical: /\b(?:diagnosis|disorder|trauma response|abuse dynamic|coercion|infidelity|unsafe consent)\b/i,
  signsOnlyLeakage: /\b(?:house|ascendant|descendant|midheaven|imum coeli|cusp|house ruler)\b/i,
  unnecessaryOrbPrecision: /\b(?:orb(?:\s+of)?\s*(?:\d+(?:\.\d+)?|one|two|three|four|five|six|seven|eight|nine|ten)\s*(?:degrees?|°)?|close and exact|(?:aspect|trine|square|opposition|sextile|conjunction|quincunx)\s+(?:is\s+)?exact|exact\s+(?:aspect|trine|square|opposition|sextile|conjunction|quincunx)|(?:under|within|nearly|less than)\s+(?:one|\d+(?:\.\d+)?)\s+degrees?|\d+(?:\.\d+)?\s+degrees?\s+(?:apart|from exact))\b/i,
  impliedNatalActivation: /\b(?:personal\s+)?activation\s+(?:means|shows|suggests).{0,80}\b(?:current|currently|now|pressing)\b|\bcurrently pressing\b|\bpressing on something close to you\b/i,
  personalActivationQualitativeOverreach: /\b(?:personal activation|natal relevance)\b[\s\S]{0,300}\b(?:unpredictab(?:ility|le)|inspir(?:ation|ed)|clarif(?:y|ies|ied|ying|ication)|destabili(?:ze|zes|zed|zing|zation)|current timing|currently|right now|this season|makes? you|means? you|shows? that you|you (?:tend to|usually|always|become|act|react))\b|\b(?:unpredictab(?:ility|le)|inspir(?:ation|ed)|clarif(?:y|ies|ied|ying|ication)|destabili(?:ze|zes|zed|zing|zation))\b[\s\S]{0,220}\b(?:personal activation|natal relevance)\b/i,
  aspectChainInvention: /\b(?:opposition|trine|square|sextile|conjunction|quincunx)\s+(?:links?|connects?)\s+(?:this|the|a)\s+.{0,50}\b(?:chain|rulership|dispositor)\b/i,
  rulershipAsAspect: /\b(?:Sun|Moon|Mercury|Venus|Mars|Jupiter|Saturn|Uranus|Neptune|Pluto|Chiron)\s+(?:is\s+)?disposed\s+by\s+(?:Sun|Moon|Mercury|Venus|Mars|Jupiter|Saturn|Uranus|Neptune|Pluto|Chiron)\s*,?\s+(?:which\s+is\s+)?(?:an?\s+)?(?:conjunction|opposition|square|trine|sextile|quincunx)\s+aspect\b/i,
  genericDispositorChain: /\bdispositor chains?\b|\b(?:rulership|dispositor)\s+(?:chain|sequence)\b|\b(?:the|this|a)\s+chain\s+(?:tracing|leading|running|ending|going)\s+(?:back\s+)?(?:to|through|from)\s+(?:Sun|Moon|Mercury|Venus|Mars|Jupiter|Saturn|Uranus|Neptune|Pluto|Chiron)\b/i,
  privilegedPerception: /\b(?:sharpens?|gives|offers|provides)\s+(?:you|your).{0,35}\b(?:read|sense)\s+(?:of|on)\s+(?:(?:hidden|social|group|unspoken)\s+){0,2}(?:undercurrents|signals|dynamics|people)\b|\b(?:sense|read|pick up on)\s+(?:(?:hidden|social|group|unspoken)\s+){1,2}(?:undercurrents|signals|dynamics)\b|\b(?:shapes?|influences?|guides?)\s+how\s+you\s+(?:read|sense)\s+(?:a\s+room|a\s+(?:friend\s+)?group|people|social\s+dynamics)\b|\bfirst impression\s+(?:can|may|might)?\s*(?:feel|seem)\s+(?:complete|convincing|certain|accurate)\b|\b(?:feeling|sense)\s+of\s+knowing\s+(?:can|may|might)?\s*(?:arrive|come)\s+(?:fast|quickly|immediately)\b/i,
  categoricalCertaintyOrChange: /\b(?:feel|feels|seem|seems)\s+(?:sure|certain)\s+(?:right away|fast|immediately)\b|\b(?:conclusion|assessment|belief).{0,30}\bsettled fast\b|\b(?:change|update).{0,20}\b(?:all at once|by a real overhaul|wholesale)\b|\b(?:immediate|rapid|sudden)\s+(?:overhaul|transformation|reinvention|change)\b|\b(?:you|that part of you)\s+already\s+(?:know|knows|has learned)\s+how\b|\b(?:counterevidence|counterweight).{0,80}\b(?:shows|proves|confirms|demonstrates).{0,80}\b(?:already|reliably)\s+(?:developed|built|learned|practiced|self-correct)\b|\byou\s+(?:have|already have|have already)\s+(?:developed|built|learned)\s+(?:a )?(?:reliable )?(?:self-correction|habit|skill)\b/i,
  driveWorkAllocationRepetition: /\b(?:before|when)\s+(?:deciding|choosing)\s+how\s+(?:much|intensely)\s+(?:to\s+)?(?:engage|push|apply(?:\s+yourself)?|exert)\b[^.!?]{0,100}\b(?:task|job|work)\b[^.!?]{0,100}\b(?:importance|size|worth|matters?)\b|\b(?:size|importance|worth|what matters?)\s+of\s+(?:the\s+)?(?:task|job|work)\b[^.!?]{0,100}\b(?:how\s+much|how\s+intensely)\s+(?:effort|force|energy|push)\b/i,
  explicitClaimNegation: /\b(?:does not|doesn't|do not|don't|is not|isn't|are not|aren't|cannot|can't|never|no proof|not evidence|not confirmation|does nothing to prove|not that|not currently)\b/i
} as const;

export function hasAffirmedClaim(text: string, pattern: RegExp) {
  return text
    .split(/(?:[.!?;]|—|\bbut\b|\byet\b)+/i)
    .some((clause) => pattern.test(clause) && !reportDetectors.explicitClaimNegation.test(clause));
}
